name: Backuo Firestore

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

env:
  PROJECT_ID: loan-shark-dev
  BUCKET: gs://backup-colectify-test-01

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET